# Copyright IBM Corp. and others 2019
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] https://openjdk.org/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0

# Generated by: mkdocker.sh --dist=centos --gitcache=no --version=7 --cuda

# To use this docker file:
# First, copy your public ssh key into authorized_keys.
# Then, in the directory containing the Dockerfile, authorized_keys
# file, and known_hosts file, run:
#   docker build --file Dockerfile .
#
# To start a container based on the resulting image, run this command:
#   docker run -it <image>

FROM nvcr.io/nvidia/cuda:12.0.0-devel-ubuntu18.04 AS cuda-dev

FROM quay.io/centos/centos:7 AS base

# Install required OS tools.

RUN yum -y update \
 && yum install -y epel-release \
 && yum -y install \
    alsa-lib-devel \
    automake \
    bind-utils \
    bison \
    bzip2 \
    ca-certificates \
    cpio \
    cups-devel \
    curl-devel \
    elfutils-libelf-devel \
    expat-devel \
    file-devel \
    file-libs \
    flex \
    fontconfig \
    fontconfig-devel \
    freetype-devel \
    gettext \
    gettext-devel \
    glibc \
    glibc-common \
    glibc-devel \
    gmp-devel \
    lbzip2 \
    libdwarf \
    libdwarf-devel \
    libffi-devel \
    libstdc++-static \
    libX11-devel \
    libXext-devel \
    libXi-devel \
    libXrandr-devel \
    libXrender-devel \
    libXt-devel \
    libXtst-devel \
    make \
    mesa-libGL-devel \
    mpfr-devel \
    ntp \
    numactl-devel \
    openssh-clients \
    openssh-server \
    openssl-devel \
    perl-CPAN \
    perl-DBI \
    perl-devel \
    perl-ExtUtils-MakeMaker \
    perl-GD \
    perl-IPC-Cmd \
    perl-libwww-perl \
    perl-Time-HiRes \
    systemtap-devel \
    texinfo \
    unzip \
    vim \
    wget \
    xorg-x11-server-Xvfb \
    xz \
    zip \
    zlib-devel \
 && yum clean all

# Install autoconf.
RUN cd /tmp \
 && wget --progress=dot:mega -O autoconf.tar.gz https://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz \
 && tar -xzf autoconf.tar.gz \
 && cd autoconf-2.69 \
 && ./configure --build=$(rpm --eval %{_host}) \
 && make \
 && make install \
 && cd .. \
 && rm -rf autoconf.tar.gz autoconf-2.69

# Install gcc-7.5.
RUN cd /usr/local \
 && wget --progress=dot:mega -O gcc-7.tar.xz 'https://ci.adoptopenjdk.net/userContent/gcc/gcc750+ccache.x86_64.tar.xz' \
 && tar -xJf gcc-7.tar.xz --strip-components=1 \
 && ln -sf ../local/bin/gcc-7.5 /usr/bin/gcc \
 && ln -sf ../local/bin/g++-7.5 /usr/bin/g++ \
 && ln -sf gcc /usr/bin/cc \
 && ln -sf g++ /usr/bin/c++ \
 && rm -f gcc-7.tar.xz

# Install gcc-11.2.
RUN cd /usr/local \
 && wget --progress=dot:mega -O gcc-11.tar.xz 'https://ci.adoptopenjdk.net/userContent/gcc/gcc112.x86_64.tar.xz' \
 && tar -xJf gcc-11.tar.xz \
 && rm -f gcc-11.tar.xz

# Install ant.
RUN cd /tmp \
 && wget --progress=dot:mega -O ant.zip https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip \
 && unzip -q ant.zip -d /opt \
 && ln -s apache-ant-1.10.5 /opt/ant \
 && ln -s /opt/ant/bin/ant /usr/bin/ant \
 && wget --progress=dot:mega -O ant-contrib.tar.gz https://sourceforge.net/projects/ant-contrib/files/ant-contrib/1.0b3/ant-contrib-1.0b3-bin.tar.gz \
 && tar -xzf ant-contrib.tar.gz \
 && mv ant-contrib/ant-contrib-1.0b3.jar /opt/ant/lib \
 && rm -rf ant-contrib ant.zip ant-contrib.tar.gz

# Install git.
RUN cd /tmp \
 && wget --progress=dot:mega -O git.tar.gz https://www.kernel.org/pub/software/scm/git/git-2.5.3.tar.gz \
 && tar -xzf git.tar.gz --no-same-owner \
 && cd git-2.5.3 \
 && make prefix=/usr/local all \
 && make prefix=/usr/local install \
 && cd .. \
 && rm -rf git.tar.gz git-2.5.3

# Update automake.
RUN cd /tmp \
 && wget --progress=dot:mega -O automake.tar.gz http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz \
 && tar -xzf automake.tar.gz \
 && cd automake-1.15 \
 && ./configure \
 && make \
 && make install \
 && cd .. \
 && rm -rf automake.tar.gz automake-1.15

# Update gettext.
RUN cd /tmp \
 && wget --progress=dot:mega -O gettext.tar.gz http://ftp.gnu.org/gnu/gettext/gettext-0.20.1.tar.gz \
 && tar -xzf gettext.tar.gz \
 && cd gettext-0.20.1 \
 && ./autogen.sh --skip-gnulib \
 && ./configure --disable-nls \
 && make \
 && make install \
 && cd .. \
 && rm -rf gettext.tar.gz gettext-0.20.1

# Update make.
RUN cd /tmp \
 && wget --progress=dot:mega -O make.tar.gz https://github.com/mirror/make/archive/4.1.tar.gz \
 && tar -xzf make.tar.gz \
 && cd make-4.1 \
 && ACLOCAL_PATH=/usr/share/aclocal autoreconf -i \
 && ./configure \
 && make update \
 && make \
 && make install \
 && ln -s make /usr/local/bin/gmake \
 && cd .. \
 && rm -rf make.tar.gz make-4.1

# Install nasm.
RUN cd /tmp \
 && wget --progress=dot:mega -O nasm.tar.gz https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.gz \
 && tar -xzf nasm.tar.gz \
 && cd nasm-2.15.05 \
 && ./configure -prefix=/usr/local \
 && make install \
 && cd .. \
 && rm -rf nasm.tar.gz nasm-2.15.05

# Add user home and copy authorized_keys and known_hosts.
RUN useradd -ms /bin/bash --uid 1000 jenkins --home-dir /home/jenkins \
 && mkdir /home/jenkins/.ssh \
 && chmod 700 /home/jenkins/.ssh
COPY authorized_keys known_hosts /home/jenkins/.ssh/
RUN chmod -R go= /home/jenkins/.ssh

# Copy header files necessary to build a VM with CUDA support.
RUN mkdir -p /usr/local/cuda/nvvm
COPY --from=cuda-dev /usr/local/cuda-12.0/include      /usr/local/cuda/include
COPY --from=cuda-dev /usr/local/cuda-12.0/nvvm/include /usr/local/cuda/nvvm/include
ENV CUDA_HOME=/usr/local/cuda

# Install cmake.
RUN cd /tmp \
 && wget --progress=dot:mega -O cmake.tar.gz https://cmake.org/files/v3.11/cmake-3.11.4.tar.gz \
 && tar -xzf cmake.tar.gz \
 && cd cmake-3.11.4 \
 && export LDFLAGS='-static-libstdc++' \
 && ./configure \
 && make \
 && make install \
 && cd .. \
 && rm -rf cmake.tar.gz cmake-3.11.4

# Install python.
RUN cd /tmp \
 && wget --progress=dot:mega -O python.tar.xz https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz \
 && tar -xJf python.tar.xz \
 && cd Python-3.7.3 \
 && ./configure --prefix=/usr/local \
 && make \
 && make install \
 && cd .. \
 && rm -rf python.tar.xz Python-3.7.3

# Run ldconfig to discover newly installed shared libraries.
RUN for dir in lib lib64 lib/x86_64-linux-gnu ; do echo /usr/local/$dir ; done > /etc/ld.so.conf.d/usr-local.conf \
 && ldconfig

# Configure sshd.
RUN mkdir /var/run/sshd \
 && sed -i -e 's|#PermitRootLogin|PermitRootLogin|' \
           -e 's|#RSAAuthentication.*|RSAAuthentication yes|' \
           -e 's|#PubkeyAuthentication.*|PubkeyAuthentication yes|' /etc/ssh/sshd_config

# SSH login fix so user is not kicked off after login.
RUN sed -i -e 's|session\s*required\s*pam_loginuid.so|session optional pam_loginuid.so|' /etc/pam.d/sshd

# Expose SSH port.
EXPOSE 22

# Download and install boot JDKs.
RUN cd /tmp \
 && wget --progress=dot:mega -O jdk8.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && wget --progress=dot:mega -O jdk11.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && wget --progress=dot:mega -O jdk17.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/17/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && wget --progress=dot:mega -O jdk21.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/21/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && wget --progress=dot:mega -O jdk23.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/23/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && mkdir -p /home/jenkins/bootjdks/jdk8 /home/jenkins/bootjdks/jdk11 /home/jenkins/bootjdks/jdk17 /home/jenkins/bootjdks/jdk21 /home/jenkins/bootjdks/jdk23 \
 && tar -xzf jdk8.tar.gz --directory=/home/jenkins/bootjdks/jdk8/ --strip-components=1 \
 && tar -xzf jdk11.tar.gz --directory=/home/jenkins/bootjdks/jdk11/ --strip-components=1 \
 && tar -xzf jdk17.tar.gz --directory=/home/jenkins/bootjdks/jdk17/ --strip-components=1 \
 && tar -xzf jdk21.tar.gz --directory=/home/jenkins/bootjdks/jdk21/ --strip-components=1 \
 && tar -xzf jdk23.tar.gz --directory=/home/jenkins/bootjdks/jdk23/ --strip-components=1 \
 && rm -f jdk*.tar.gz
RUN chown -R jenkins:jenkins /home/jenkins
USER jenkins
