# Copyright IBM Corp. and others 2019
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] https://openjdk.org/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0

# Generated by: mkdocker.sh --dist=ubuntu --gitcache=no --version=22 --cuda

# To use this docker file:
# First, copy your public ssh key into authorized_keys.
# Then, in the directory containing the Dockerfile, authorized_keys
# file, and known_hosts file, run:
#   docker build --file Dockerfile .
#
# To start a container based on the resulting image, run this command:
#   docker run -it <image>

FROM nvcr.io/nvidia/cuda:12.0.0-devel-ubuntu18.04 AS cuda-dev

FROM public.ecr.aws/lts/ubuntu:22.04 AS base

# Install required OS tools.

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Toronto

RUN apt-get update \
 && apt-get install -qq -y --no-install-recommends \
    ant \
    ant-contrib \
    autoconf \
    build-essential \
    ca-certificates \
    cmake \
    cpio \
    curl \
    file \
    g++-11 \
    gcc-11 \
    gdb \
    git \
    libasound2-dev \
    libcups2-dev \
    libdwarf-dev \
    libelf-dev \
    libexpat1-dev \
    libffi-dev \
    libfontconfig \
    libfontconfig1-dev \
    libfreetype6-dev \
    libnuma-dev \
    libssl-dev \
    libx11-dev \
    libxext-dev \
    libxrandr-dev \
    libxrender-dev \
    libxt-dev \
    libxtst-dev \
    make \
    nasm \
    openssh-client \
    openssh-server \
    perl \
    pkg-config \
    ssh \
    systemtap-sdt-dev \
    unzip \
    wget \
    xvfb \
    zip \
    zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*

# Add user home and copy authorized_keys and known_hosts.
RUN useradd -ms /bin/bash --uid 1000 jenkins --home-dir /home/jenkins \
 && mkdir /home/jenkins/.ssh \
 && chmod 700 /home/jenkins/.ssh
COPY authorized_keys known_hosts /home/jenkins/.ssh/
RUN chmod -R go= /home/jenkins/.ssh

# Copy header files necessary to build a VM with CUDA support.
RUN mkdir -p /usr/local/cuda/nvvm
COPY --from=cuda-dev /usr/local/cuda-12.0/include      /usr/local/cuda/include
COPY --from=cuda-dev /usr/local/cuda-12.0/nvvm/include /usr/local/cuda/nvvm/include
ENV CUDA_HOME=/usr/local/cuda

# Install python.
RUN cd /tmp \
 && wget --progress=dot:mega -O python.tar.xz https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz \
 && tar -xJf python.tar.xz \
 && cd Python-3.7.3 \
 && ./configure --prefix=/usr/local \
 && make \
 && make install \
 && cd .. \
 && rm -rf python.tar.xz Python-3.7.3

# Run ldconfig to discover newly installed shared libraries.
RUN for dir in lib lib64 lib/x86_64-linux-gnu ; do echo /usr/local/$dir ; done > /etc/ld.so.conf.d/usr-local.conf \
 && ldconfig

# Configure sshd.
RUN mkdir /var/run/sshd \
 && sed -i -e 's|#PermitRootLogin|PermitRootLogin|' \
           -e 's|#RSAAuthentication.*|RSAAuthentication yes|' \
           -e 's|#PubkeyAuthentication.*|PubkeyAuthentication yes|' /etc/ssh/sshd_config

# SSH login fix so user is not kicked off after login.
RUN sed -i -e 's|session\s*required\s*pam_loginuid.so|session optional pam_loginuid.so|' /etc/pam.d/sshd

# Expose SSH port.
EXPOSE 22

# Download and install boot JDKs.
RUN cd /tmp \
 && wget --progress=dot:mega -O jdk8.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && wget --progress=dot:mega -O jdk11.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && wget --progress=dot:mega -O jdk17.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/17/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && wget --progress=dot:mega -O jdk21.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/21/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && wget --progress=dot:mega -O jdk23.tar.gz https://api.adoptopenjdk.net/v3/binary/latest/23/ga/linux/x64/jdk/openj9/normal/adoptopenjdk \
 && mkdir -p /home/jenkins/bootjdks/jdk8 /home/jenkins/bootjdks/jdk11 /home/jenkins/bootjdks/jdk17 /home/jenkins/bootjdks/jdk21 /home/jenkins/bootjdks/jdk23 \
 && tar -xzf jdk8.tar.gz --directory=/home/jenkins/bootjdks/jdk8/ --strip-components=1 \
 && tar -xzf jdk11.tar.gz --directory=/home/jenkins/bootjdks/jdk11/ --strip-components=1 \
 && tar -xzf jdk17.tar.gz --directory=/home/jenkins/bootjdks/jdk17/ --strip-components=1 \
 && tar -xzf jdk21.tar.gz --directory=/home/jenkins/bootjdks/jdk21/ --strip-components=1 \
 && tar -xzf jdk23.tar.gz --directory=/home/jenkins/bootjdks/jdk23/ --strip-components=1 \
 && rm -f jdk*.tar.gz
RUN chown -R jenkins:jenkins /home/jenkins
USER jenkins
